  
sudo: required
services:
- docker
arch:
  - arm64
matrix:
  include:
   - os: linux
     arch: arm64
language: bash
script:
# prepare qemu
# - docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- travis_wait 120 sleep infinity & docker build -t chriswoj/docker-kaldi-asr .
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker tag uptospace/docker-kaldi-asr chriswoj/kaldi-asr:0.1
    docker push uptospace/kaldi-asr:0.1
  fi
